name: Mockup-Workflow-Test

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Choose your env
        options: 
        - develop
        - test
        - preprod
        - prod

jobs:
  build-dev:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.name, 'develop')

    steps:
      - name: Testting development env
        run: echo ${{ github.event.inputs.name }}
  
  build-qa:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.name, 'test')

    steps:
      - name: Testting development env
        run: echo ${{ github.event.inputs.name }}
  
  build-pp:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.name, 'preprod')
    steps:
      - name: Testting development env
        run: echo ${{ github.event.inputs.name }}